### ISSUE TITLE
原則 1のタイトルに余計な数字が入っている

### ISSUE THREAD

**Issue by bakera** [waic/wai-wcag-quickref#11]
https://waic.github.io/wai-wcag-quickref/#principle1 のタイトルが、「原則 1 – 1 知覚可能」となっていて、余計な数字が入っているように思います。
「原則 1 – 知覚可能」が正しいはずです。

なお、他の原則は問題ないようです。
https://waic.github.io/wai-wcag-quickref/#principle2
https://waic.github.io/wai-wcag-quickref/#principle3
https://waic.github.io/wai-wcag-quickref/#principle4

**Comment by momdo** [comment]
理屈の上ではこの修正でよいはずですが… GitHub Pagesででも直っていない…？

**Comment by momdo** [comment]
今度こそ修正できました。
